### PR TITLE
Add two new attributes in Article class

### PR DESCRIPTION
**Pull request by migueldvb**
Added bibstem and grant cached attributes to Article. They are now organized by alphabetical order

### CODE REVIEW

**Comment by vsudilov** [comment]
Hi,

AFAIK bibstem was removed since it isn't actually returned by the ADS, see i.e. https://github.com/andycasey/ads/pull/62 . Is the same true for `grant`?

**Comment by jonnybazookatone** [comment]
Yes, `bibstem` is not a stored value in the search engine, so it's indexed for searching but isn't returned.

I believe `grant` isn't complete in terms of the corpus coverage, and so it isn't advised to be used until it's been fully implemented by ADS.

In the future, I'd close most (if not all) requests to add new fields unless it's done by the ADS team. Since we closed issue #61, there is a list maintained by the ADS (https://adsabs.github.io/help/search/comprehensive-solr-term-list) -- in theory ;-).

**Comment by vsudilov** [comment]
I'd vote for including `grant` (even though its not complete) and removing `bibstem`. @migueldvb, thoughts ?

**Comment by migueldvb** [comment]
Oh I missed #62. `+1` for keeping grant maybe as a different PR.

**Comment by vsudilov** [comment]
FYI you can just add a commit to `migueldvb:search` and it will be auto-updated in this PR.

**Comment by migueldvb** [comment]
Thanks. I have updated this PR.

**Pull request merged**
