### PR TITLE
Minor change to README opening sentence

### PR DESCRIPTION
**Pull request by eteq**
Admittedly, this is incredibly pedantic of me.  But there it is anyway ;)

### CODE REVIEW

**Comment by vsudilov** [comment]
Thanks :)

**Comment by andycasey** [comment]
But what about physics?

**Comment by eteq** [comment]
@andycasey - you mean "astrophysics", or just straight-up "physics"?  Annoyingly, some physicists do in fact survive without using ADS ;)

**Comment by jonnybazookatone** [comment]
Thanks for the PR, and albeit pedantic, I'd like to chip in that the ADS has ~8 million *physics* papers, and ~2 million *astronomy* papers. So, there will be angry Physicists if the ADS went down too ;-).

**Pull request merged**
