### PR TITLE
Response JSON decoder and UTF detection

### PR DESCRIPTION
**Pull request by takerukoushirou**
In some cases the returned data was garbled, and it turns out that the response object of the requests package had to guess the encoding via the chardet library, as the content-type returned by the server didn't include a character set. In a particular case, the guessed ("apparent") encoding was TIS-620 instead of UTF-8.

As the data returned is UTF-8 encoded JSON, this is easily fixed by hinting the response on the encoding to use. I added a response hook for the session to set the encoding to a configured value, if no explicit encoding was given by the server and before the text content of the response is used, defaulting to UTF-8. The previous guessing behaviour can be restored by setting the configuration value to `None`.

### CODE REVIEW

**Comment by vsudilov** [comment]
LGTM, but it would be nice for this to be upstreamed to the ADS API, and I'm pretty sure it would be trivial to do... @jonnybazookatone any chance that could be put on the backlog?

**Comment by jonnybazookatone** [comment]
Sure. Can you give an example in which you ran into this problem @takerukoushirou and I'll open a ticket.

**Comment by takerukoushirou** [comment]
Sure, that particular case for example was the paper returned by query `identifier:2012Natur.486..502B` for the fields 'bibcode', 'title', 'author', 'bibstem', 'pubdate', 'property', 'pub'.

A simplified but complete example, with the difference that chardet detects ISO-8859-2 instead of TIS-620 as only the title is queried:
```python
import ads

ads.config.token = '...'
papers = ads.SearchQuery(q='identifier:2012Natur.486..502B', fl=['title'])

for paper in papers:
    print(paper.title[0])
    print(repr(paper.title[0]))
```
The server returns the content-type `application/json`, and the Python `requests` package only checks for a charset definition in the content-type or defaults to ISO-8859-1 for text content in the requests utility function `get_encoding_from_headers` (i.e. in our case this yields none). Once the text property of the response object is queried, and as no encoding was set, the apparent (=guessed via chardet) encoding property is used to transform the content before an attempt is made to decode the JSON data.

The simplest solution is to return a content-type of `application/json; charset=utf-8`.

**Comment by jonnybazookatone** [comment]
@takerukoushirou thanks for the commits, they look useful. 

However, I'd suggest you move your latest commit `f113331` to a separate pull request as it isn't directly related to default encoding issue you raised. As I'm the one blocking this in terms of work, the other unrelated changes should get merged faster.

**Comment by takerukoushirou** [comment]
@jonnybazookatone I didn't know nor expected that GitHub automatically adds new commits to an existing pull request. I'll check whether it's possible to fix that somehow; the latest commit should indeed become an own pull request once I'm sure I didn't miss any other fields.

**Comment by jonnybazookatone** [comment]
Yep :smile:, if you push to the same branch you made the PR from (in your case takerukoushirou:master), then it'll also be automatically pushed to both the branch and the PR. 

You could just manually delete the changes and re-push as they're minor changes, or read this: https://github.com/blog/2019-how-to-undo-almost-anything-with-git. 

I'd also read this https://guides.github.com/introduction/flow, which will help avoid any future problems.

**Comment by takerukoushirou** [comment]
I just purged commit `f113331` and looks like GitHub automatically cleaned up this PR. Thank you–good to know that a PR is tied to and updated with its branch. So next time a separate branch as I originally intended to do, but didn't due to the small size of the modifications 😄

**Comment by jonnybazookatone** [comment]
OK. I've looked a bit into this and I feel this is something that should be changed on the client side, as originally intended by @takerukoushirou.

What's happening is the `APIResponse` class is passing `response.text` to build any of the `Response` objects we have (https://github.com/andycasey/ads/blob/master/ads/base.py#L95). As pointed out, `requests` will either use `response.encoding` defined by the response header to enforce the encoding, or delegate to `chardet` to guess the encoding. `chardet` gets it wrong in many cases (in the context highlighted in this PR).

One solution is to add `charset: utf-8` in the headers, however, the RFC of JSON is that by default it is a type of UTF, 8, 16, or 32. So if you're expecting JSON, you don't need to guess the encoding type, because it should be (if RFC compliant) UTF.

This problem has been raised before, e.g., http://stackoverflow.com/questions/13067748/converting-to-utf-8-again, and a PR was made to handle the situation https://github.com/kennethreitz/requests/pull/909, where the `json()` method will guess which UTF formatting is being used https://github.com/kennethreitz/requests/blob/master/requests/models.py#L800.

We can fix it in the following ways:
  * Apply this PR, but this adds a bit of complexity, extra thing to track, and I think we restrict ourselves a little more in comparison to `json()`, although I don't think in terms of this client it's that important.

  * Use `json()` in `APIResponse`: this will touch several files `base.py`, `search.py`, `metrics.py`, `export.py`, and all the relevant tests. 

  * Modify `c = cls(HTTPResponse.text)` to `c = cls(HTTPResponse.content.encode('utf-8')`: simplest, but fairly hacky and essentially the same as this PR.

I feel the `json()` solution is the most robust and compliant, but is a little more effort. For example:

base.py:
```python
c = cls(HTTPResponse) # cls(HTTPResponse.text)
```
search.py:
```python
def __init__(self, response): # (self, raw)
    self._raw = response.text # raw
    self.json = response.json() # json.loads(raw)
```

Thoughts @vsudilov @andycasey @takerukoushirou?

**Comment by takerukoushirou** [comment]
I also agree that switching to `json()` is the cleanest and most robust solution, as it defers the JSON-handling to the requests library, including proper UTF detection.

Or is there any specific reason that `text` has been used instead of `json()` @vsudilov @andycasey?

**Comment by vsudilov** [comment]
Hard to judge without seeing a PR, but your snippet seems like a good approach.

**Comment by andycasey** [comment]
No specific reason AFAIK. No objections from me, either: switching to `json()` seems like the right thing to do.

**Comment by jonnybazookatone** [comment]
You happy to update the PR @takerukoushirou?

**Comment by takerukoushirou** [comment]
Sure 😄

**Comment by jonnybazookatone** [comment]
Looks good to me. I'd merge unless anyone has objections.

**Comment by vsudilov** [comment]
:+1:

**Pull request merged**
