### PR TITLE
Support Python 3

### PR DESCRIPTION
**Pull request by barentsen**
It would be great if `ads` supported Python 3!

This PR contains the changes needed for the unit tests to pass under both 2.7 and 3.4 on my machine.  (But I must warn that I am not an expert on Python 3 porting.)

### CODE REVIEW

**Comment by barentsen** [comment]
Note that Travis fails before actually running the tests -- but I can't figure out why?

**Comment by barentsen** [comment]
(note: if merged, #11 can be closed)

**Comment by andycasey** [comment]
¡Hola!

Thanks @barentsen! I will merge this now before addressing the newer issues that have cropped up,.. including the massive, awesome, work by @vsudilov! 

Travis was failing because the ADS API key is a private environment variable on Travis, and is inaccessible to pull requests otherwise someone could just print out all private PRs.

**Comment by andycasey** [comment]
Hmm, Travis still falls over on 3.4: https://travis-ci.org/andycasey/ads/jobs/69227629

I will look into this now.

**Pull request merged**
