### PR TITLE
misc: first iteration ISSUE_TEMPATE.md

### PR DESCRIPTION
**Pull request by vsudilov**
Context: 
https://github.com/blog/2111-issue-and-pull-request-templates

Using https://github.com/TalAter/open-source-templates as the first iteration

### CODE REVIEW

**Comment by vsudilov** [comment]
Is this something that would benefit devs and/or users?

Should the template be modified before putting live?

**Comment by jonnybazookatone** [comment]
Benefit for devs, especially without having to ask back-and-forth questions at the beginning that spams the issue. Also for users if they want to look at tickets and see if it's related to their issue.

I'd also consider the PR template (or contributing) if you're thinking of the issues template.

**Comment by andycasey** [comment]
Just letting you know that I will get to this in the upcoming weekend. Thanks for opening this @vsudilov

**Comment by andycasey** [comment]
👍 :shipit:

**Pull request merged**
